# This workflow will build a release of a Java-project with Maven
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow requires two input parameters, the development version and the intended release version.


name: Release CI with Maven

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to checkout to build the release."
        required: true
        default: "main"
      releaseVersion:
        description: "Default version to use when preparing a release or a branch."
        required: true
        default: "A.B.C"
      developmentVersion:
        description: "Default version to use for new local working copy."
        required: true
        default: "A.B.D-SNAPSHOT"

jobs:

  release:

    permissions:
      contents: write
      pages: write
      packages: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        cache: maven

    - name: View settings.xml
      run: cat /home/runner/.m2/settings.xml        

    - name: Configure Git user
      run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"      

    - name: Create Maven Release
      run: mvn -B release:prepare release:perform
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
